#project Week 4 Coursera Data Science
#read.table reads file using separator with any number of space with option sep=""
test <- read.table("UCI HAR Dataset/test/X_test.txt", sep = "")
train <- read.table("UCI HAR Dataset/train/X_train.txt", sep = "")
#take a look at the data
dim(test) # can also see this info from the environment panel
dim(train)
#dim shows that the data can be merged row-wise. Ignored the inertial signals data
#use rbind to merge the rows
#1. Merges the training and the test sets to create one data set.
har <- rbind(train,test)
#2. Extracts only the measurements on the mean and standard deviation 
#for each measurement.
#read in the list of features or variables
features <- read.table("UCI HAR Dataset/features.txt", sep = "")
#select only features that are means and standard deviations
#use grepl to logically select which one 
#has the expression "mean" or "std" in their name
index <- with(features, grepl("mean|std", V2)) #notice that the OR operator is within the same double quotes
selection <- features[index,]
#get rid of autogenerated rownames
rownames(selection) <- NULL
#convert rownos into a vector to act as index
rowvector <- selection[["V1"]]
class(rowvector)
#3. Uses descriptive activity names to name the activities in the data set
#create df meanstd that contains only mean and std deviation
#using the index rowvector from the merged dataset
meanstd <- har[rowvector] #at this point meanstd has var names V1-V522
head(meanstd)
#get the type of activities and their description (e.g. standing)
#from the y_test.txt, y_train.txt and activity_labels.txt files
trnact <- read.table("UCI HAR Dataset/train/y_train.txt", sep = "\n")
tstact <- read.table("UCI HAR Dataset/test/y_test.txt", sep = "\n")
actdesc <- read.table("UCI HAR Dataset/activity_labels.txt", sep = "")
#add activity descriptions to type of activities files using dplyr left_join()
#to maintain the order of the activities in the type of activities
library(dplyr)
trnact <- left_join(trnact,actdesc, by=c("V1" = "V1"))
tstact <- left_join(tstact,actdesc, by=c("V1" = "V1"))
#combine the activity type and descriptions from the two files
acttype <- rbind(trnact,tstact)
#attach activity description to the selected har dataset
meanstd <- cbind(acttype,meanstd)
head(meanstd)
#get subject ids to include into the meanstd df
trnsub <- read.table("UCI HAR Dataset/train/subject_train.txt", sep = "\n")
tstsub <- read.table("UCI HAR Dataset/test/subject_test.txt", sep = "\n")
sub <- rbind(trnsub,tstsub)
#attach subjects to selected har
meanstd <- cbind(sub,meanstd)
head(meanstd)
#convert selected variable names into a character vector
vars <- as.character(selection[["V2"]])
length(vars)
#append additional columns (subject, act type and description)
#to existing variable names
vars <- c("subjectid", "actid", "type of activity", vars)
#rename all columns
names(meanstd) <- vars
str(meanstd)
#4. Appropriately labels the data set with descriptive variable names.
#Read existing features into Excel to copy and replace with descriptive names
#copy from Excel into clipboard and read into R
descvars<-read.table(pipe("pbpaste"), sep="\t", header=F)
#convert dt to character vector
vars <- as.character(descvars[["V1"]])
str(vars)
#add first three variables
vars <- c("subjectid", "actid", "type of activity", vars)
#rename all the variables in the main meanstd
names(meanstd) <- vars
str(meanstd)
#5. Create a second, independent tidy data set with the average of 
#each variable for each activity and each subject.
subdf <- aggregate(meanstd[,4:82], by = list(meanstd$actid,meanstd$subjectid), FUN = mean)
head(subdf)
write.table(subdf, file = "tidydata.txt", row.names = FALSE)
